---
# tasks file for install
- name: Install bind
  package:
    name: 
      - bind9
      - bind9utils
      - bind9-doc
      - bind9-dnsutils  
    state: present

- name: regexp file named
  lineinfile:
    path: /etc/default/named
    line: 'OPTIONS="-u bind -4"'
    regexp: '^#?OPTIONS="-u bind"'
    state: present

- name: coppy named conf file
  template:
    src: named.conf.j2
    dest: /etc/bind/named.conf
    owner: root
    group: bind
    mode: 0644
  notify: restart bind9

- name: Coppy named conf local file
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: 0644
  notify: restart bind9

- name: coppy forward file
  template:
    src: db.forward.j2
    dest: /etc/bind/db.{{ domain }}
    owner: root
    group: bind
    mode: 0777
  notify: restart bind9

- name: coppy reverse file
  template:
    src: db.reverse.j2
    dest: /etc/bind/db.{{ rev_domain }}
    owner: root
    group: bind
    mode: 0777
  notify: restart bind9

- name: regexp resolv file
  lineinfile:
    path: /etc/resolv.conf
    line: 'nameserver {{ ipv4 }}'
    regexp: 'nameserver 127.0.0.53'
    state: present
  notify: restart bind9 
