---
- name: Creat user on a Linux
  remote_user:
  hosts: "{{ hosts }}"
  become: yes
  vars:
    - user: vais
    - password: 123321@a
  tasks:
     - name: Create a login user
       ansible.builtin.user:
         name: khiemnguyen
         shell: /bin/bash
         groups: sudo
         state: present 

     - name: Disable SSH password authentication
       become: true
       lineinfile:
         dest: /etc/ssh/sshd_config
         regexp: '^#?\s*PasswordAuthentication\s'
         line: 'PasswordAuthentication no'
         state: present
     - name: restart services sshd
       ansible.builtin.service:
         name: sshd
         state: restarted
         enabled: true  
